Update all views when changing showAll
We cannot update all views at once, because this happens:
```
file:///usr/share/harbour-ttrss-cnlpete/qml/models/FeedModel.qml:51:
TypeError: Cannot read property 'categoryId' of null
```

Tested on sailfish
Closes #142